### ISSUE TITLE
Is this the latest version?

### ISSUE THREAD

**Issue by jnthnclrk** [tommusrhodus/ebor-page-builder#1]
This repo doesn't appear to contain as many blocks as I got when purchasing Pivot from Theme Forest. Just wondering if its up to date as I want to check if it's worth writing custom blocks for other purposes.

**Comment by tommusrhodus** [comment]
Hey there,

Pivot contains multiple blocks which extend the functionality of this plugin, what you're seeing is the base "any theme" functionality.

Cheers

**Comment by jnthnclrk** [comment]
k, thanks
